# Generated by Django 5.1.5 on 2025-04-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0002_complaint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('Electricity', 'Electricity'), ('Water', 'Water'), ('Potholes', 'Potholes'), ('Garbage Collection', 'Garbage Collection'), ('Street Lights', 'Street Lights'), ('Sewage', 'Sewage'), ('Other', 'Other')], default='Electricity', max_length=50),
        ),
    ]
