# Generated by Django 5.2 on 2025-04-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0003_alter_complaint_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(default='electricity', max_length=255),
        ),
    ]
